## app containers spec

version: '3.5'
services:
  traefik:
    image: traefik:1.4-alpine
    command: --web --docker --docker.domain=docker.localhost
    networks:
      - proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  anchor:
    image: system-pharos-anchor-go
    container_name: pharos-anchor
    volumes:
      - ~/pharos-anchor/data/db:/data/db
    labels:
      - "traefik.frontend.rule=PathPrefixStrip: /pharos-anchor"
      - "traefik.port=48099"
    networks:
      - proxy
    depends_on:
      - traefik
networks:
  proxy:
    driver: bridge
    name: proxy
