// Code generated by MockGen. DO NOT EDIT.
// Source: src/controller/resource/node/nodecontroller.go

// Package mock_node is a generated GoMock package.
package mock_node

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCommand is a mock of Command interface
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// GetNodeResourceInfo mocks base method
func (m *MockCommand) GetNodeResourceInfo(nodeId string) (int, map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "GetNodeResourceInfo", nodeId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(map[string]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNodeResourceInfo indicates an expected call of GetNodeResourceInfo
func (mr *MockCommandMockRecorder) GetNodeResourceInfo(nodeId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeResourceInfo", reflect.TypeOf((*MockCommand)(nil).GetNodeResourceInfo), nodeId)
}

// GetAppResourceInfo mocks base method
func (m *MockCommand) GetAppResourceInfo(nodeId, appId string) (int, map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "GetAppResourceInfo", nodeId, appId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(map[string]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAppResourceInfo indicates an expected call of GetAppResourceInfo
func (mr *MockCommandMockRecorder) GetAppResourceInfo(nodeId, appId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppResourceInfo", reflect.TypeOf((*MockCommand)(nil).GetAppResourceInfo), nodeId, appId)
}
