/*******************************************************************************
 * Copyright 2017 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *******************************************************************************/

// Code generated by MockGen. DO NOT EDIT.
// Source: registry.go

// Package mock_registry is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCommand is a mock of Command interface
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// AddDockerRegistry mocks base method
func (m *MockCommand) AddDockerRegistry(body string) (int, map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "AddDockerRegistry", body)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(map[string]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddDockerRegistry indicates an expected call of AddDockerRegistry
func (mr *MockCommandMockRecorder) AddDockerRegistry(body interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDockerRegistry", reflect.TypeOf((*MockCommand)(nil).AddDockerRegistry), body)
}

// DeleteDockerRegistry mocks base method
func (m *MockCommand) DeleteDockerRegistry(registryId string) (int, error) {
	ret := m.ctrl.Call(m, "DeleteDockerRegistry", registryId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDockerRegistry indicates an expected call of DeleteDockerRegistry
func (mr *MockCommandMockRecorder) DeleteDockerRegistry(registryId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDockerRegistry", reflect.TypeOf((*MockCommand)(nil).DeleteDockerRegistry), registryId)
}

// GetDockerRegistries mocks base method
func (m *MockCommand) GetDockerRegistries() (int, map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "GetDockerRegistries")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(map[string]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDockerRegistries indicates an expected call of GetDockerRegistries
func (mr *MockCommandMockRecorder) GetDockerRegistries() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDockerRegistries", reflect.TypeOf((*MockCommand)(nil).GetDockerRegistries))
}

// GetDockerRegistry mocks base method
func (m *MockCommand) GetDockerRegistry(registryId string) (int, map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "GetDockerRegistry", registryId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(map[string]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDockerRegistry indicates an expected call of GetDockerRegistry
func (mr *MockCommandMockRecorder) GetDockerRegistry(registryId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDockerRegistry", reflect.TypeOf((*MockCommand)(nil).GetDockerRegistry), registryId)
}

// GetDockerImages mocks base method
func (m *MockCommand) GetDockerImages(registryId string) (int, map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "GetDockerImages", registryId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(map[string]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDockerImages indicates an expected call of GetDockerImages
func (mr *MockCommandMockRecorder) GetDockerImages(registryId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDockerImages", reflect.TypeOf((*MockCommand)(nil).GetDockerImages), registryId)
}

// DockerRegistryEventHandler mocks base method
func (m *MockCommand) DockerRegistryEventHandler(body string) (int, error) {
	ret := m.ctrl.Call(m, "DockerRegistryEventHandler", body)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DockerRegistryEventHandler indicates an expected call of DockerRegistryEventHandler
func (mr *MockCommandMockRecorder) DockerRegistryEventHandler(body interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DockerRegistryEventHandler", reflect.TypeOf((*MockCommand)(nil).DockerRegistryEventHandler), body)
}
