/*******************************************************************************
 * Copyright 2017 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *******************************************************************************/
// Code generated by MockGen. DO NOT EDIT.
// Source: messenger.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockhttpInterface is a mock of httpInterface interface
type MockhttpInterface struct {
	ctrl     *gomock.Controller
	recorder *MockhttpInterfaceMockRecorder
}

// MockhttpInterfaceMockRecorder is the mock recorder for MockhttpInterface
type MockhttpInterfaceMockRecorder struct {
	mock *MockhttpInterface
}

// NewMockhttpInterface creates a new mock instance
func NewMockhttpInterface(ctrl *gomock.Controller) *MockhttpInterface {
	mock := &MockhttpInterface{ctrl: ctrl}
	mock.recorder = &MockhttpInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockhttpInterface) EXPECT() *MockhttpInterfaceMockRecorder {
	return m.recorder
}

// DoWrapper mocks base method
func (m *MockhttpInterface) DoWrapper(req *http.Request) (*http.Response, error) {
	ret := m.ctrl.Call(m, "DoWrapper", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoWrapper indicates an expected call of DoWrapper
func (mr *MockhttpInterfaceMockRecorder) DoWrapper(req interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoWrapper", reflect.TypeOf((*MockhttpInterface)(nil).DoWrapper), req)
}

// MockMessengerInterface is a mock of MessengerInterface interface
type MockMessengerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMessengerInterfaceMockRecorder
}

// MockMessengerInterfaceMockRecorder is the mock recorder for MockMessengerInterface
type MockMessengerInterfaceMockRecorder struct {
	mock *MockMessengerInterface
}

// NewMockMessengerInterface creates a new mock instance
func NewMockMessengerInterface(ctrl *gomock.Controller) *MockMessengerInterface {
	mock := &MockMessengerInterface{ctrl: ctrl}
	mock.recorder = &MockMessengerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMessengerInterface) EXPECT() *MockMessengerInterfaceMockRecorder {
	return m.recorder
}

// SendHttpRequest mocks base method
func (m *MockMessengerInterface) SendHttpRequest(method, url string, dataOptional ...[]byte) (int, string, error) {
	varargs := []interface{}{method, url}
	for _, a := range dataOptional {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendHttpRequest", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendHttpRequest indicates an expected call of SendHttpRequest
func (mr *MockMessengerInterfaceMockRecorder) SendHttpRequest(method, url interface{}, dataOptional ...interface{}) *gomock.Call {
	varargs := append([]interface{}{method, url}, dataOptional...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHttpRequest", reflect.TypeOf((*MockMessengerInterface)(nil).SendHttpRequest), varargs...)
}
